### ISSUE TITLE
Disable one element of the grid ?

### ISSUE THREAD

**Issue by Kaherdin** [ducksboard/gridster.js#100]
How can I disable only one element in my gridster ? 

&lt;div class=&quot;gridster&quot;&gt;
    &lt;ul&gt;
        &lt;li&gt; class=&quot;not-draggable&quot;&gt;Content&lt;/li&gt;
        &lt;li&gt;class=&quot;draggable&quot;&gt;Content&lt;/li&gt;
        &lt;li&gt;class=&quot;draggable&quot;&gt;Content&lt;/li&gt;
        &lt;li&gt;class=&quot;draggable&quot;&gt;Content&lt;/li&gt;
    &lt;/ul&gt;
&lt;/div&gt;

So I want that the first one can't be draggable.
Thx.

**Comment by Pointy-hair** [comment]
Hi I would also be interest in achieving this functionality although I would imagine that these would need to be fixed elements that are not moveable.
Thanks 
Andrew

**Comment by TheMoonLite** [comment]
+1. very necessary

**Comment by dustmoo** [comment]
I have semi-support for static widgets in my fork here:

https://github.com/dustmoo/gridster.js

I am looking into the feasibility of merging my changes into root project.

Thanks.

Dustin

**Comment by Superdrac** [comment]
No news on this ?

**Comment by vieron** [comment]
Duplicate of #130.

This was submitted before #130 but much more activity there.
