### ISSUE TITLE
How to save new layout after dragging and refresh the page ?

### ISSUE THREAD

**Issue by 12343954** [ducksboard/gridster.js#111]
show me the code demo please , cookies ,ajax , whatever others, thank you , i think other people need this also

**Comment by jbbodinier** [comment]
Hello same probleme. I want to save the position and reload it after a few day, for an planning application ?
How to save all the list content and position ?
thank you for your answers !

**Comment by marcovanest** [comment]
```
$(".gridster>ul").gridster({

    widget_margins: [12.5, 12.5],

    widget_base_dimensions: [75, 75],

        serialize_params: function($w, wgd) {
        return {
            x: wgd.col,
            y: wgd.row,
            width: wgd.size_x,
            height: wgd.size_y,
            id: $($w).attr('id'),
            class: $($w).attr('class')
        };
    },

    draggable: {
                stop: function(event, ui){
                  //console.log(this.$player.attr('id'));
                  //console.log(this.$player.attr('class'));
                  //console.log(this.$player.coords().grid);

                  $oWidgets = this.serialize_changed();
                  saveWidgets($oWidgets);
                }
            }

  });
```

**Comment by 12343954** [comment]
thank you very much , @marcovanest

**Comment by bowersdesign** [comment]
@12343954 did that work? I was wondering if you could share the html? I tried that code but nothing happens...I suspect I am missing something.

**Comment by 12343954** [comment]
@bowersdesign , yes, see my code in the page , http://cooloogoo.com

**Comment by ryandingle** [comment]
hey bro. mine says saveWidgets undefined ?
how to debug ?

**Comment by Jessekevon** [comment]
Does anyone have a working example of this? I have a codepen trying to implement 'save state' after refreshing the page but I cannot seem to get it to work. Any help would be greatly appreciated!

http://codepen.io/jessekevon/pen/eNgEro

**Comment by kavyaLinkEZ** [comment]
What saveWidgets($oWidgets); function do?
@marcovanest
