### ISSUE TITLE
gridster boxes don't move correctly

### ISSUE THREAD

**Issue by Reflic** [ducksboard/gridster.js#114]
Hey guys,

i have included all necessary files (jquery.gridster.js and jquery.gridster.css) in my application and have used the following html markup.

``` html
<div class="gridster">
    <ul>
        <li data-row="1" data-col="4" data-sizex="2" data-sizey="1">Test</li>
        <li data-row="2" data-col="4" data-sizex="2" data-sizey="1">Lib</li>
        <li data-row="3" data-col="3" data-sizex="2" data-sizey="1">Ya</li>
        <li data-row="1" data-col="4" data-sizex="2" data-sizey="1">tll</li>
        <li data-row="2" data-col="4" data-sizex="2" data-sizey="1">safasf</li>
        <li data-row="3" data-col="4" data-sizex="2" data-sizey="1">wfwf</li>
    </ul>
</div>
```

But it does not work. As you can see in this example at jsfiddle. http://jsfiddle.net/aQVDG/1/

The boxes are not created at the right place, and i can place boxes on other boxes.

I don't know if i have forgot anything or if this is a bug.

It looks that this repository is not maintained anymore, but maybe someone will fork the repo and fix the bugs.

**Comment by hayesmaker** [comment]
You' haven't found bugs, you're just not using it correctly.. You're widget dimensions don't match with what you have 140px x 2 is not 300px is it?

Also your data-rows and data-cols look messed up.

**Comment by 12343954** [comment]
You are missing the css code of gridster
i update it，http://jsfiddle.net/12343954/aQVDG/6/
check it

**Comment by Reflic** [comment]
Yeah, sorry it was my mistake. Thank you for the fast help. The issue can be closed.
