### ISSUE TITLE
NOT WORKING WITH JQUERY 1.9.1 !!

### ISSUE THREAD

**Issue by yossibens** [ducksboard/gridster.js#134]
Please help, gridster is not working with the latest version of Jquery.
You can test right HERE : http://jsfiddle.net/agryson/Lp6sB/10/

**Comment by Dwtbc** [comment]
Add the jQuery migrate plugin also, it should help: http://code.jquery.com/jquery-migrate-1.1.1.js

http://jquery.com/download/

**Comment by yossibens** [comment]
Yeah i tried but still doesn't work :(

**Comment by Dwtbc** [comment]
In what ordre have you placed your plugins?

It should be something like this:
js/jquery-1.9.1.js"
js/jquery-migrate-1.1.1.js
js/jquery.gridster.js

and then try placing the gridster functions:

  var gridster;

  $(function(){

```
gridster = $(".gridster > ul").gridster({
    widget_margins: [10, 10],
    widget_base_dimensions: [140, 140],
    min_cols: 6
}).data('gridster');
```

  });

after the last closing div and before the closing body tag

**Comment by yossibens** [comment]
like this

<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>

<script src="http://code.jquery.com/jquery-migrate-1.1.1.min.js"></script>

<script src="js/gridster.js" type="text/javascript" charset="utf-8"></script>

**Comment by yossibens** [comment]
http://code.jquery.com/jquery-1.9.1.min.js
http://code.jquery.com/jquery-migrate-1.1.1.min.js
js/jquery.gridster.js

**Comment by Dwtbc** [comment]
And you have tried using the the uncompressed versions?

**Comment by Dwtbc** [comment]
I have made a simple example with the 1.9.1. plugin: http://jsfiddle.net/Pre9k/16/

See if this can help you

**Comment by yossibens** [comment]
YEAHH !!! thank you so much !!! it worksssssss (it was the class READY which block all the script)

**Comment by Dwtbc** [comment]
Perfect, glad I could help

**Comment by gotwig** [comment]
What about gridster upstream support for 1.9.1 . Is there any work being done at all?

**Comment by gotwig** [comment]
We have to optimize it now already for jquery 2.0 I think. That would be the best choice.

**Comment by dustmoo** [comment]
I will be working on adding upstream support for jquery 2.0 on my branch.
