### ISSUE TITLE
Restrict the drag region to a specific area, not the entire widget?

### ISSUE THREAD

**Issue by jim-at-miramontes** [ducksboard/gridster.js#135]
The canonical use of gridster seems to be one where the entire object can be touched to indicate that a drag operation is to be started.  Is it possible to limit that touchable region to a specific area (div) in the object, perhaps indicated by an icon of some sort?  I'd like to be able to use gridster with objects that have other (mouse-sensitive) things in them, and I don't want the user (let along gridster :) getting confused about what's supposed to happen.  Any thoughts?

**Comment by jim-at-miramontes** [comment]
Followup: If you've seen Things on the Mac, this is the kind of thing I'm thinking about.

**Comment by FRickReich** [comment]
All you need is a drag handle for that.

**Comment by jim-at-miramontes** [comment]
Aha -- found it: https://github.com/ducksboard/gridster.js/pull/59 .  Thanks!

**Comment by FRickReich** [comment]
yes thats exactly what i ment! sorry that i couldnt find it as fast for you :/

**Comment by jim-at-miramontes** [comment]
np; thanks again!
