### ISSUE TITLE
Is it possible to restore a gridster view to a previous state?

### ISSUE THREAD

**Issue by jim-at-miramontes** [ducksboard/gridster.js#136]
I'm using gridster in a situation where, for a variety of reasons, I provide buttons that allow the user to take the grid into and out of "draggable mode".  I'd like to set things up so that there's something like a "restore original order" button, that returns all the elements of the grid to the way they were originally.  I'm thinking that update_widget_position() might be of use here, but I'm not sure if it is, or exactly how it would be used to do this.  Is there any advice out there about this?

**Comment by wokket** [comment]
I am in exactly the same position.  For simplicity I opted to just refresh the page if the user 'cancels' their drag/drop/configuration session.

**Comment by jim-at-miramontes** [comment]
Yeah, that's what I'm doing, too.  Kind of the Cowards's Way Out :), but I don't see any other way to deal with it at the moment.

**Comment by gotwig** [comment]
Serialize the grid into an object/array , and then restore from there.

**Comment by poagester** [comment]
@gotwig, can you provide an example for those of us that are not as familiar with this code?

**Comment by thaiberious** [comment]
// To save layout   

var gridster = $(".gridster ul").gridster({
        serialize_params: function ($w, wgd) {
            return {
                id: wgd.el[0].id,
                col: wgd.col,
                row: wgd.row,
                size_x: wgd.size_x,
                size_y: wgd.size_y
            };
        },
        draggable: {
            stop: function () {
                var json = JSON.stringify(_gridster.serialize());
                SaveConfiguration (json); // AJAX Call to save JSON string
            }
        }
    }).data('gridster');

// To load layout (Do this before initializing gridster)

```
if (layout != '') {
    var json = jQuery.parseJSON(layout);
    for (i = 0; i < json.length; i++) {
        var item = json[i];
        $('#' + item.id).attr('data-row', item.row).attr('data-col', item.col);
    }
}
```

**Comment by vieron** [comment]
Example building a grid from a serialized object: http://gridster.net/demos/grid-from-serialize.html
