### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by gotwig** [ducksboard/gridster.js#139]
Is this project dead?

If so, we should bring our afford together, and make a fork of it.

Look at the pull requests, and the last commits.

Basic things like a good ready callback are missing as well.

**Comment by wulczer** [comment]
Hi, I'm Jan, from Ducksboard. It's not dead, just resting :)

But seriously, unlike the parrot from the sketch, it's not dead. We've been really swamped lately and haven't been able to dedicate enough effort to maintaining Gridster... now we've reached the conclusion that it's time to give control of the project to the community.

In the next few days we'll choose new maintainers from the people who submitted patches and helped with issues. Grid on! :)

**Comment by FRickReich** [comment]
i think dustmoo (https://github.com/dustmoo/gridster.js) made the most extensive changes, i didnt really check alot of the other ones thoo.

**Comment by dustmoo** [comment]
Thanks Fredrick, I have but I too am pretty busy.

I would love to get some collaborators together and keep things moving
forward.

Let us know ducksboard.

**Comment by FRickReich** [comment]
yeah i noticed that you are way more busy then you told me 2 weeks ago, no problem hehe.

**Comment by dustmoo** [comment]
Yes, when the project isn't currently related to billable items it takes
some motivation to keep on it. That said, I have some time this week or
updates. :)

**Comment by antonkulaga** [comment]
> I would love to get some collaborators together and keep things moving
> forward.

I think you should provide better documentation/samples for it and its architecture, it will make it easier to learn it and contribute. Because without digging in its sources it is uneasy to understand how to do some basic stuff like putting constrains on drag and drop ( I want to assign these events only to widget headers and not to all of its area)

**Comment by floribon** [comment]
Woah dustmoo thanks a lot for all your work! I just switched from the standard gridster lib to yours and it's much better. I really hope you'll find people and keep things move, I'm not sure I have the required experience but let the community know if you need help on some fields.

**Comment by dustmoo** [comment]
Thanks! It needs some work and is breaking in some applications. I am trying desperately to carve out some time for updates. :)
