### ISSUE TITLE
New Feature Request or i don't know how... activate or disable drag and drop

### ISSUE THREAD

**Issue by triperwiper** [ducksboard/gridster.js#14]
Is possible by variable or option to activate or disable the drag and drop function, because I put buttons in the widgets and when I push the buttons the widget activate the drag and drop function.

**Comment by vieron** [comment]
There are two methods to [enable](http://gridster.net/docs/classes/Gridster.html#method_enable) and [disable](http://gridster.net/docs/classes/Gridster.html#method_disable) dragging in gridster. I also added a reference to these methods in the homepage (http://gridster.net/#enable_method).

Btw, I've made that `<buttons>` (as inputs, textareas and selects) don't trigger the dragging.

Maybe it makes sense to allow ignore custom HTML elements, well with a established class (.ignore) or via config option with a CSS selector string.

**Comment by vikassaklecha** [comment]
vieron,
I have a question on the similar lines, im trying to allow dragging on when you are on a certain part of the container.
How can i allow the container to be dragable only when you are on that part of the container?
I did try the enable and disable methods, on dragable.start i check if im on that certain part of the container then enable otherwise disable. The container sticks to the mouse and does not leave it as it loses drag property.

draggable: {
                start: function(event, ui){
                     var element = ui.helper;
                     var child = element.children('header');
                     if(child.is(':hover')) {
                        this.enable();
                     } else {
                         this.disable();
                     }
                }
            }

**Comment by uskiano** [comment]
I have exactly the same question.. i need to be able to drag just from one element in the container.. but don't know how...

**Comment by jeanfs** [comment]
Well, I'll try to explain how I did that. I'm not a developer and I don't know so much about coding, but check out my solution for this:

My HTML markup for the elements of the grid is like this:

``` html
<li class="widget wg-warnings gs_w" data-row="2" data-col="2" data-sizex="1" data-sizey="2">
    <div class="panel-header">
        ...
    </div>
    <div class="panel-body">
        ...
    </div>
</li>
```

So I want to stop dragging if the user click and drag the body of the widget (wich is the div that will receive a couple of different contents). But how? Just stopping the propagation of the event "mousedown". Then I did this:

``` javascript
$(".panel-body").mousedown(function(event){
    event.stopPropagation();
});
```

**Comment by uskiano** [comment]
Your solution works awesome!! thx a lot jeanfs!!

**Comment by jeanfs** [comment]
I'm glad it helped. =)
