### ISSUE TITLE
Feature Request for widget size

### ISSUE THREAD

**Issue by lukeholder** [ducksboard/gridster.js#15]
Ability to change size of a block on the fly. (in API) This would probably cause some reflow.

related is also that serialize should return the sizey and sizex

![image](http://lukeholder.me/share/Brandagram-20120807-155507.jpg)

**Comment by codingisacopingstrategy** [comment]
I have a hard time expressing in words how much I +1 this feature request
!

**Comment by afincha** [comment]
I REALLY want this feature added. If you could make the tiles resizeable by dragging the bottom right corner of a tile, with the rest of the tiles reacting appropriately, that would be perfect! 

Also, awesome work so far, guys. Really enjoying this plugin.

**Comment by maebert** [comment]
Agreed, resizing -- or at least the ability to refresh manually to take into account changes in `data-sizex` and `data-sizey` would be fab!

**Comment by ghz** [comment]
Totally agree, it would be a very interesting feature !

**Comment by bmla** [comment]
For size_y size_x see #23. But agreed, serialize should return size_y and size_x.

I totally agree with the rest of the guys, we need auto resize height so we can put different size of content to each box.    We need dynamic height :D 

Thanks!
Btw, nice plugin.
