### ISSUE TITLE
freely rearranged?

### ISSUE THREAD

**Issue by TheMoonLite** [ducksboard/gridster.js#151]
how to make sure that the elements can be freely rearranged in any direction, not like now that all the elements are automatically attaches to the top

**Comment by dustmoo** [comment]
If you are asking if you can swap widgets from side to side, you'll need to use my fork of the project here:

https://github.com/dustmoo/gridster.js

Check out the sample for applicable settings.

**Comment by TheMoonLite** [comment]
http://img526.imageshack.us/img526/9418/545656k.jpg

like http://jqueryui.com/draggable/
but that the item moves through the cells (grid) as they are now
