### ISSUE TITLE
Impossible to create a widget bigger than 5 cols

### ISSUE THREAD

**Issue by ghost** [ducksboard/gridster.js#16]
Hi guys, first thank you for you wonderfull work !!!
I'm trying to create something with it but I have an issue.

THE WIDGET 22 col width doesn't work, can you help ?

Here is the link of the page :
http://floflow.me/_sites/zoning/

Thank you in advance for your time !

**Comment by vieron** [comment]
Hi @floflow !

It was hardoded to 6... Now by default is 6 but you can set to 22 in the initialization via the [max_size_x/max_size_y](http://gridster.net/#max_size_x_opt) option. 

Note that your code is throwing an error trying to access to gridster.add_widget method outside the document ready and without declaring gridster var.

Thanks for the feedback :)

**Comment by ghost** [comment]
Thank you very much for you reactivity and for the fix ;)

You rocks !

**Comment by ghost** [comment]
Just a little thing !
When I put max_size_x: 22 I can only make a  data-sizex="22"
I have to put max_size_x: 23 to suceed ^^
