### ISSUE TITLE
How to transmit positions through online checkout

### ISSUE THREAD

**Issue by cassing** [ducksboard/gridster.js#160]
Hi all. Question here.

This involves custom product building.  As an example, let's say a customer is building a quilt with blocks of different fabric patterns provided.  If the customer wants to purchase the layout they created using the provided fabric patterns, is there a way to "transmit" their custom quilt to the merchant so that they know what the customer created?

If not, does anyone know of such a thing that I could implement.

Disclaimer: I am an HTML & CSS person, not a jQuery or javascript one.

Thanks muchly.

**Comment by dustmoo** [comment]
Hi Cassing,

Unfortunately you'll need to understand Javascript to be able to pass the coords around.

There is a function call "serialize" that you can use to store the positions in an object and then pass that serialized object around your site.

Good luck.

**Comment by cassing** [comment]
Thanks, dustmoo.

I do work with javascript regularly; I'm just not a maestro. 

So if someone could point me to some more info on the serialize function, that would be much appreciated.  Also, would it be able to be passed through a checkout process?

Thanks again.

**Comment by dustmoo** [comment]
Hi Cassing,

Understood, we all have to start somewhere. This may help you:

https://github.com/ducksboard/gridster.js/issues/121
