### ISSUE TITLE
Support drag handle that has content.

### ISSUE THREAD

**Issue by cpsubrian** [ducksboard/gridster.js#161]
Currently, if you want to utilize a custom drag handle it cannot have any child dom nodes inside it due to this chunk:

https://github.com/ducksboard/gridster.js/blob/master/src/jquery.draggable.js#L343-L349

This worked for me, though I'm not sure if its the most performant way to do this. Delegation would be preferable, but that would require more refactoring I think.

``` js
fn.ignore_drag = function(event) {
    if (this.options.handle) {
        return !($(event.target).is(this.options.handle) || $(event.target).parents(this.options.handle).length);
    }
    return $.inArray(event.target.nodeName, this.options.ignore_dragging) >= 0;
};
```

**Comment by dustmoo** [comment]
By custom drag handle, do you mean an child element that is used to drag the widget around? Rather than the widget itself?

**Comment by cpsubrian** [comment]
Yep

**Comment by dustmoo** [comment]
You can use this config parameter to specify the draggable element, I haven't tested it on child elements but you should be able to use the draggable items option to make child the draggable item:

```
$(".gridster ul").gridster({
    widget_margins: [5, 5],
    widget_base_dimensions: [50, 50],
    draggable: {
       items: ".child_element"
    }
}).data('gridster');
```

Have you tried this already?

**Comment by cpsubrian** [comment]
I've been using:

``` js
$(".gridster ul").gridster({
    widget_margins: [5, 5],
    widget_base_dimensions: [50, 50],
    draggable: {
       handle: ".drag-handle"
    }
}).data('gridster');
```

Unless I'm misunderstanding you, I want the whole `<li>` to be draggable, but I want users to only be able to initiate drag from a 'handle' (its a title-bar).  The `draggable -> handle` setting is supposed to be what allows this, but the section of code above is a little naive I think, and assumes the event that initiates the dragging will be exactly the 'handle' element.  In my case (I would assume a common one), the handle contains addition elements (an `<h4>`, a close button, etc.).

**Comment by cpsubrian** [comment]
Let me setup a fiddle that will illustrate the problem more clearly :)

**Comment by cpsubrian** [comment]
Hopefully this helps illustrate the issue. Let me know if this doesn't make sense.

http://jsfiddle.net/xLTLr/2/

**Comment by d9705996** [comment]
I have updated your fiddle.  You can now move the Fanta widget by the title

http://jsfiddle.net/xLTLr/3/

Is this what you are looking for?

**Comment by boyzoid** [comment]
The only way I can get the handle property to function correctly is if the element I specify does not have any child elements. ANy ways around this?

**Comment by udeebsdev** [comment]
Is there any update on this issue? Is Gridster team going to implement the bug fix?

**Comment by vieron** [comment]
Related to #334.

Also `ignore_dragging` config option can be a function that receives the event as first argument. So you can prevent drag from being ignored.

**Comment by ajmajma** [comment]
@vieron I cannot find an example or get this to work, how exactly do i use ignore_dragging to fix this? thanks!

**Comment by vieron** [comment]
@ajmajma http://jsbin.com/fuwunuyi/6/edit

**Comment by ajmajma** [comment]
@vieron thank you! I still can't seen to get this to work correctly for me, I have a bunch of div's inside my top drag handle, do I define the handle then use ignore_dragging?  I very much appreciate your help.
