### ISSUE TITLE
error after the latest commits - coords is not a function

### ISSUE THREAD

**Issue by badtant** [ducksboard/gridster.js#162]
just updated to the latest version and now i get the following error.
even tested it with the samplecode on gridster.net and gets the same error so it's not just my code.

Uncaught exception: TypeError: '$({
                        left: this.baseX + ((col - 1) \* this.min_widget_width),
                        top: this.baseY + (row -1) \* this.min_widget_height,
                        width: this.min_widget_width,
                        height: this.min_widget_height,
                        col: col,
                        row: row,
                        original_col: col,
                        original_row: row
                    }).coords' is not a function

**Comment by dustmoo** [comment]
Hi badtant,

If you are loading the script from source you'll need to include the gridster plugins. The error above is caused because you have not loaded:

```
jquery.coords.js
```

The dist compiles these plugins into the library.

**Comment by badtant** [comment]
ahhhh, makes sense. thanks and sorry for my mistake :)

**Comment by dustmoo** [comment]
No worries.
