### ISSUE TITLE
Change element which is dragable?

### ISSUE THREAD

**Issue by 416BC** [ducksboard/gridster.js#164]
I've tried specifying the draggable element through some code I found here on github, but it only made the element draggable. What I mean is, I know the entire <li> is clickable to drag. I want the enitre <li> to drag still when clicked, but I want to specify an inner element to be clicked on to initiate the dragging of the entire <li>.

<li><div id="head">header</div><div>content goes here and is 90% height</div></li>

I want the entire <li> to move, but only be triggered by clicking the "#head" is this possible?

**Comment by dustmoo** [comment]
I think this issue may answer your question:

https://github.com/ducksboard/gridster.js/issues/161#issuecomment-17026388
