### ISSUE TITLE
Grid does not resize and items overlap after drag

### ISSUE THREAD

**Issue by aaustermiller** [ducksboard/gridster.js#167]
See this fiddle http://jsfiddle.net/PdjLE/389/ 
When you try to drag number 5 under number 7, the positioning gets messed up and the long items go on top of each other. This seems to happen with any of the widgets with a large size-y attribute get dragged.

**Comment by dustmoo** [comment]
The object overlap is a known problem. This has to do with how gridster triggers different movement events at different times, I am looking into which calls are causing the overlap issue.

**Comment by martincastell** [comment]
Could you please elaborate a bit more on the different movement events causing the overlap issue?

**Comment by aaustermiller** [comment]
I know it has been awhile, but it is not necessarily when you drag.  The issue occurs when the grid initially loads.  I have found that the issue seemingly fixed when you either increase the height portion of the widget base dimensions and sorting the unordered list so that the nodes follow left to right, top to bottom order.

**Comment by maxgalbu** [comment]
this is fixed by https://github.com/ducksboard/gridster.js/pull/149

**Comment by vieron** [comment]
Fixed in v0.2.0
