### ISSUE TITLE
How to check if an element has a certain row and col value after dragging?

### ISSUE THREAD

**Issue by anthonybarsotti** [ducksboard/gridster.js#168]
I'm trying to check to see if a list item has been dragged to a certain row and col position and if it has I want to add a class to that list item. Has anyone tried this?

**Comment by dustmoo** [comment]
In each jquery wrapped widget has a coords() object that can tell you the row and col that it currently occupies:

```
$widget = $("#widget_id");
var col = $widget.coords().grid.col;
var row = $widget.coords().grid.row;
```

You can use those properties to determine the current col and row of a widget.
