### ISSUE TITLE
Grid not being applied either before or after dynamic code creation properly

### ISSUE THREAD

**Issue by AlexRoscoe** [ducksboard/gridster.js#171]
I am using the angular library to dynamically load a set of widgets (ng-repeat business) and I have found two issues on either side of my desired outcome. 

First: I form the list in the html by ng-repeating the gridster <li>'s. The problem is (I believe) that the data I am repeating over is being retreived by a http request so it is not arriving in time to make it into the html before gridster assumes it is done. 
   Symptoms: single wide elements stacked vertically on initial load. 
                     works on refresh every time. 

Second: After seeing this I decided to add the html pieces to gridster manually once my http request comes in using add_widget. I then $compile to connect them to angular and everything is 'working'  but now it works on initial load perfectly.. but on refresh the widgets seem to only have 1-2 columns and stack vertically within them.. even though I am intentionally setting 5 cols and have values from 1-5 for each element.. they're being ignored. 

code example (Angular controller): 

function WidgetCtrl($scope, $http, $compile) {
    $http.get('widgets/widgetList.json').success(function(data) {
        $scope.widgets = data;
        var gridster = $(".gridster ul").gridster().data('gridster');
        gridster.options.widget_base_dimensions = [140, 140];
        gridster.options.min_cols = 4;
        gridster.options.min_rows = 3;
        gridster.options.max_size_x = 2; 
        for (var i = 0; i < 10; i++) {
            var url = "<li><div ng-include=\"'";
            url += data[i].url;
            url += "'\"></div></li>";
            // Compile new html with angular to allow it to bind up
            url = $compile(url)($scope);
            gridster.add_widget(url, data[i].sizeX, data[i].sizeY, data[i].col, data[i].row);
        }
    }); 
}

**Comment by dustmoo** [comment]
Have you debugged the code to see if it is running properly on refresh? I would add some console.log functions to make sure everything is triggering first and that your response data is what you expect it to be. I havn't worked with Angular, is it possible that it is caching the request somehow?

All in all, it still could be gridsters fault. :)

**Comment by AlexRoscoe** [comment]
The solution turned out to initialize it with nothing when it wanted to (at the start) and then add the widgets later.

**Comment by dustmoo** [comment]
Thanks!
