### ISSUE TITLE
how to use draggable.start / draggable.stop?

### ISSUE THREAD

**Issue by lwojcik** [ducksboard/gridster.js#18]
Hi. I'm playing around with Gridster (http://jsfiddle.net/lwojcik/ZCkwz/1/) and trying to bind events on start/stop dragging. The doc says that it's possible to use options draggable.start / draggable.stop. However, I have no clue how to use them (where to put them in the code). Could you provide any example of gridster call with start, drag and stop events?

**Comment by tx2z** [comment]
HI, I've "solved" the same problem :)

you have to use something like that:

```
        $(".gridster ul").gridster({
            widget_margins: [10, 10],
            widget_base_dimensions: [140, 140],
            draggable: {
                stop: function(event, ui){ 
                             // your events here
                }
            }
        });
```

Hope it help.

Saludos

**Comment by lwojcik** [comment]
That's exactly what I needed. Thanks!

**Comment by hayesmaker** [comment]
agree with the poster, the documentation doesn't make this clear enough.

**Comment by mdzzaman** [comment]
many many thanks.

**Comment by ntourne** [comment]
Guys - Once stop function is called - Do you know how to get the new x and y positions? Thanks.

**Comment by bclennox** [comment]
It looks like the best way is to call `serialize()` or `serialize_changed()`, since the operation could affect more than just the widget that was dragged.
