### ISSUE TITLE
save positions in database

### ISSUE THREAD

**Issue by n9iels** [ducksboard/gridster.js#181]
Hi everyone,

Is it possible to save the position in a MySQL database when i move a tile?

Thanks!

**Comment by dustmoo** [comment]
It isn't built in. You need to send your serialized object to your server or code that inserts into the database.

**Comment by n9iels** [comment]
could you give me a example?

**Comment by Bogardo** [comment]
``` javascript
var gridster = $(".gridster ul").gridster({
    serialize_params: function($w, wgd) {
        return {
            x: wgd.col,
            y: wgd.row,
            width: wgd.size_x,
            height: wgd.size_y,
            id: $($w).attr('id'),
            class: $($w).attr('class')
        }
    }
}).data('gridster');

var json = JSON.stringify(gridster.serialize());
```

You can then use the content of the json variable to save the data to a database.

**Comment by n9iels** [comment]
Thanks, i use the following code now:

``` javascript
$(function(){ //DOM Ready

  var gridster = $(".gridster ul").gridster({
        widget_margins: [10, 10],
        widget_base_dimensions: [140, 140],
        serialize_params: function($w, wgd) {
            return {
                id: wgd.el[0].id,
                col: wgd.col, 
                row: wgd.row,
                size_x: wgd.size_x,
                size_y: wgd.size_y
            };
        },
        draggable: {
            handle: '.handle',
            stop: function(event, ui) {

                    var positions = JSON.stringify(gridster.serialize());

                    $.post(
                      "process.php",
                      {products: positions},
                      function(data){
                          $("#result").html(data);
                      }
                    );
                  }
        }
    }).data('gridster');
```

process.php:

``` php
<?php 

$products = json_decode($_POST["products"], true);

foreach ($products as $product)
{
    echo "id: ".$product['id']."<br>";
    echo "col: ".$product['col']."<br>";
    echo "row: ".$product['row']."<br>";
    echo "size_x: ".$product['size_x']."<br>";
    echo "size_y: ".$product['size_y']."<br>";
    echo "<br>";
}

?>
```

**Comment by mrcharis** [comment]
Hi there 

I have been trying to implement the above code, but I cannot seem to get it to work.

I understand the code, that it passes the dimensions to the post.php page, I am just not sure how to go about inserting that into my mysql database

I am quite good with php / mysql I know all about insert / update etc etc 

Could you please post an example of the code you used to insert the data into the database?

I will change the above code to only save onClick, and then have a save button, but this raises more issues....

Ideally I would like to be able to save the layout with an id, preferably a name, so I could then have a database full of different layouts.

So beneath the layout I would have a text field 'layoutname' and a save button

most of this I can do, but I would like to be able to also post the name along with the dimension data.

Any help at all would be really great. 

If I figure it out beforehand I will post my efforts 

Have a nice day

**Comment by aasimkhan1410** [comment]
Hi,
I am using the same code to but I am not able to get width and height after resizing. It shows the same width and height as it is on load. I also want to fetch the content (text). How do I do that? Please help.
