### ISSUE TITLE
resize_widget - height / width of widget not updated

### ISSUE THREAD

**Issue by Rdot** [ducksboard/gridster.js#184]
Hi -

  When the resize_widget method is called,  the height / width of the widget does not change to reflect to new height / width.

**Comment by brandinchiu** [comment]
I've found this too, I have to call resize_widget then manually set the attribute size to compensate.  Very frustrating.

**Comment by MartinWeise** [comment]
Is there no way to update the grid like gridster.refresh() ?
@brandinchiu: Same here :-1:

**Comment by pipanchik** [comment]
Has anyone found an elegant solution?

**Comment by vieron** [comment]
Fixed in 195295be
