### ISSUE TITLE
Cross-Browser Compatability?

### ISSUE THREAD

**Issue by edobry** [ducksboard/gridster.js#19]
Is this compatible across most browsers? Works in Chrome and Firefox for me, but refuses to even run in IE9...

**Comment by vieron** [comment]
Gridster supports Internet Explorer 9+, Firefox, Chrome, Safari and Opera. Can you provide more details about your problem with IE9?

**Comment by xzykho** [comment]
Mine is breaking in IE, I'm just starting out to go in depth with jQuery. I don't really know what I'm doing most of the time so I hope you can help me, thanks in advance and this is such an awesome plugin. http://prodigalconcepts.com/demo/to-do-list/superman.html

**Comment by vieron** [comment]
@xzykho I just opened your url in IE9 and it works well, except the CSS transitions that are not supported. Are you referring to versions prior to 9?

**Comment by xzykho** [comment]
Thank you for your reply Javier, you were right. My bad, Great job here...
