### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by ThatRendle** [ducksboard/gridster.js#194]
Is the dustmoo fork being re-integrated into ducksboard's repo?

I need the static feature; best guess is that I should use dustmoo right now, but can switch back to ducksboard when the integration work is complete? Is that right?

**Comment by dustmoo** [comment]
Yes mark, I am launching a new site, (large one) this month. Once I do I am going to give gridster some love. :)

Thanks,

Dustin

**Comment by ThatRendle** [comment]
Great, thanks. And good luck with the launch!

**Comment by dustmoo** [comment]
Thank Mark,

I am feeling a bit like a neglectful adopted father with gridster right now
because it needs a lot of work. :) I am sure the launch will go well, but
it is a giant project, keep your fingers crossed for me.

Good luck with your project.

Dustin
