### ISSUE TITLE
Gridster is overlapping widgets when jquery ui is being used.

### ISSUE THREAD

**Issue by xmikew** [ducksboard/gridster.js#208]
Hello,

Ran across this issue when attempting to use gridster and jquery ui. In the jsfiddle if I remove jquery ui dialog and just stick with calling functions without the dialog, it works as expected. 

To duplicate, click on "add grid" with a max col of 3 or whatever you want. Add some widgets.

Then add another grid with some widgets and then reorder the widgets in the 2nd grid. You'll see they start overlapping and go all goofy. It seems to manifest itself especially if you add a grid with max_col 3 then add a grid with max_col 1. Add a couple of widgets to the 2nd grid then sort the 2nd grid widgets.

http://jsfiddle.net/mKKXz/1/

You should see something happen like this:

![gridster-overlap](https://f.cloud.github.com/assets/2590571/874255/ce26077c-f887-11e2-9f3e-5b8716b76a39.PNG)

From searching around on issues, I ran across this (issue 69) https://github.com/ducksboard/gridster.js/issues/69

which seems to be related. I attempted maxgalbu's fix but the issue was still present so not sure if it is the same issue. Feel free to make as dup if you think it is. I noticed that top was set to 0 on the second grid widgets, so it does seem related perhaps!

Thanks as always,
- Mike

**Comment by xmikew** [comment]
Seems fixed in the dustmoo fork, however i believe what triggers the bug is trying to drag a widget to the last column of a row. In dustmoo fork, it just refuses to put a widget there. In ducksboard, it does the funky overlap craziness.

\- Mike

**Comment by xmikew** [comment]
I don't think this is fixed in dustmoo's fork. Just doesn't manifiest itself the same way.
All Gridster instance options are getting overwritten by the last gridster instantiated which is causing calculations using max_cols to go wacky. (hypothesis)

\- Mike

**Comment by xmikew** [comment]
The extend of options causes this and not jquery ui as far as I can tell. This may be by design. If you want multiple grids with independent options the extend should be changed to extend({}, defaults, options). Warning: not thoroughly tested.

**Comment by simplenotezy** [comment]
I am experiencing the exact same problem - any solution to this?
