### ISSUE TITLE
Save gridster generated html layout to mysql database

### ISSUE THREAD

**Issue by mrcharis** [ducksboard/gridster.js#215]
Hi there 

I have been trying to figure out how to save my gridster layouts to my database, with no success, so far. 

Unlike other posts I would actually like to save the entire layout html code, in only one field of my database. (as opposed to saving the grid details)

I cannot figure out how to do this, I have found that gridster does not actually change the outputted source code of the page live (if you check the page source of your gridster page before and after altering your grid you will see no changes in the code)

I would like to insert the gridster grid into a ful page form and then post the entire page contents to my php upload page, as only one post variable, and then be stored into my database as one complete page layout.

Meaning that to diplay the grid in the future I only need to echo out the one DB table field.

make any sense?

Is this possible?

Any help would be great.

Have a nice day

**Comment by cybernet** [comment]
you can, but i can't figure out ... i just discovered this function `generate_grid_and_stylesheet();`

http://gridster.net/docs/classes/Gridster.html#method_generate_grid_and_stylesheet

**Comment by vieron** [comment]
Use `serialize` method to get widgets positions ([example](http://gridster.net/demos/serialize.html)), then you can build a grid from this serialized object ([example](http://gridster.net/demos/grid-from-serialize.html))
