### ISSUE TITLE
resize bug

### ISSUE THREAD

**Issue by pipanchik** [ducksboard/gridster.js#220]
For example:
http://jsfiddle.net/PrtrR/73/
resizable.handles: 'n, e, s, w',
If I pull the right edge of the green block to the left by two steps and let go - OK.
If I pull the left edge of the green block to the right by four steps and let go - grey block eats green.
Or i pull top edge of the main block to the bottom by one step and let go - user photos block eats him.

**Comment by vieron** [comment]
Fixes in 195295be
