### ISSUE TITLE
How to make correctly expandable widgets?

### ISSUE THREAD

**Issue by rrolla** [ducksboard/gridster.js#224]
I want to widget make expandable when clicked, hover, etc.

I try with something like this:

```
 $(".gridster ul li").on({
    mouseenter: function(){
        var gridster = $('.gridster ul').gridster().data('gridster');
        gridster.resize_widget( $(this), [2], [2] );
    },
    mouseleave: function(){
        var gridster = $('.gridster ul').gridster().data('gridster');
        gridster.resize_widget( $(this), [1], [1] );
    }
 });
```

But something weird happen, all expandable widgets goes to right corner :(

Here is working example: http://lvur.no-ip.biz/~edgars/gridster-test/

**Comment by rrolla** [comment]
I found where was my error;

i pass invalid arguments to this method:

```
 gridster.resize_widget( $(this), [1], [1] );
```

## should be

```
 gridster.resize_widget( $(this), 1, 1 );
```

## without square brackets!

But in http://gridster.net documentation is:

```
.resize_widget( $widget, [size_x], [size_y] )
```

## with square brackets!

Now issue has, when resize last column, sometimes goes to right, already if max_cols option given.

Sometimes, widget below not resizing correctly.

## need to check example:

http://lvur.no-ip.biz/~edgars/gridster-test/

thanks for attention ;)

**Comment by dexion** [comment]
because [size_x] - it's not required argument. it's a standart typography

**Comment by pcavalheiro** [comment]
It's possible do this with dynamic sizes?
In my case i have widgets with diferents size-x and size-y and i don't want that when mouseleave the size of widget is always 1 but their original size.. anyone can help me?
