### ISSUE TITLE
serialize example

### ISSUE THREAD

**Issue by bowersdesign** [ducksboard/gridster.js#234]
Would anyone be willing to provide the html and js for a working example of the demo layout and the use of serialize?

I'm hoping to store the layout as a cookie or save it somehow for a user so when they refresh the browser it remembers what layout they made.

Thanks.

**Comment by aaduane** [comment]
Trying to do the same thing, would love to see an example.

**Comment by vieron** [comment]
See examples here: http://gridster.net/#demos
