### ISSUE TITLE
Widget binding with Gridster and Knockout

### ISSUE THREAD

**Issue by IntStarFoo** [ducksboard/gridster.js#239]
I am new to Javascript and trying to use Gridster with Knockout. I have a database with items, and I use knockout foreach to bind them to a UL. The UL is styled with the Gridster library. Everything works great unless I try to add additional elements to the UL via the ObservableArray in the viewmodel.

Can anyone help me understand the scope and order of operations here? It feels like the Gridster library isn't doing its styling to the new widgets.

This jsfiddle shows a working demo of the issue. Notice when you double click on a widget, it creates a new one but doesn't place it in the grid. Instead, it just kind of hangs out behind.

http://jsfiddle.net/Y5swe/

**Comment by ronnyek** [comment]
InstStarFoo, I've more or less got this working... but there is a pretty big caveat. Basically I've bound data-col / data-row to properties I specify, which allows me to register_widget with the div knockout created... and likewise I can persist my changes in gridster by serializing just the position info.

The problem seems to be random cases where occasionally I'll tell gridster to position my items, and as soon as my model updates (not in position of the elements) gridster starts re-positioning stuff.

I'm going to see if I cant wrap this up into a custom binding so I can finally be done with this =)

**Comment by IntStarFoo** [comment]
Thanks for looking at it!  I added the below code to the end of the .push( new item ) function but it doesn't watch the size_x, size_y and it just feels wrong.  Especially since the Gridster library handled the first elements without issue.

$.each($(".layouts_grid2 li"), function (index, obj) {
    if (undefined !== obj.attributes && -1 === obj.attributes['class'].nodeValue.search('gs_w')) {
        //self.layout2._latestValue.register_widget(obj);
        self.layout2._latestValue.add_widget(obj);
    }
});
//self.layout2._latestValue.init();

**Comment by IntStarFoo** [comment]
I updated the JSFiddle with some extra code that manually adds the widget to the gridster... thing.  It works as far as I can tell, but I am still not sure why and / or how.  

http://jsfiddle.net/Y5swe/3/

Just after .push ing a new item into the observable array, I do this to manually add the widget to the gridster... thing.

```
    $.each($(".layouts_grid2 li"), function (index, obj) {
    if (undefined !== obj.attributes['class'] && -1 === obj.attributes['class'].nodeValue.search('gs_w')) {

        //What is going on here????
        var g = $(".gridster ul").gridster({
                widget_margins: [5, 5],
                widget_base_dimensions: [140, 140]
        }).data('gridster');  //What does .data('gridster') do?

        g.add_widget(obj);
    }
    });
```

**Comment by IntStarFoo** [comment]
Closing - Duplicate of #251

**Comment by IntStarFoo** [comment]
For Future Reference - The above JSFIddles don't work because of bad references to Gridster.js and .css.  Here is an updated version with the proper references.

http://jsfiddle.net/Be4cf/44/
