### ISSUE TITLE
Disable drag & drop completly

### ISSUE THREAD

**Issue by ghost** [ducksboard/gridster.js#25]
I would like to use this great sript on backend where working fine, but i need on the frontend as well without the drag & drop (only markup generated by the script, i would like to avoid the math part to do manually), is there any method to disable the drag & drop after load? I tried with the disable() function but i`ll get error "object has no method".

**Comment by newgi** [comment]
It's still not clear for me how to disable the drag & drop on the whole grid, could you show me an example please?

**Comment by brainTrain** [comment]
If I'm understanding what you want, you would wanna do something like this newgi:

var gridster = $(".gridster ul").gridster().data('gridster');
gridster.disable();

oooorrrr...

$(".gridster ul").gridster().data('gridster').disable()

**Comment by newgi** [comment]
Yep, I asked it as a new issue as well. Thanks :)

https://github.com/ducksboard/gridster.js/issues/58

**Comment by bhapps** [comment]
I had a problem where the above code caused other jquery plugins to conflict/stop functioning so went with 

jQuery(".gridster ul").gridster({
          widget_margins: [5, 6],
          widget_base_dimensions: [150, 150],
          draggable: {ignore_dragging: true},
          max_cols: [3],
          max_rows: [3],
      });

and all in harmony now...
