### ISSUE TITLE
Mouse over iframe breaks drag

### ISSUE THREAD

**Issue by maxmumford** [ducksboard/gridster.js#268]
Hi all,

I have a simple grid with equal size squares. Each square has a title bar set as the drag handle, and the contents is an iframe.

If I click on the title bar and start dragging, then quickly move my mouse so it leaves the drag handle element and mouses over the iframe, the drag stops. If I keep the mouse button held down and move the cursor away from the iframe, the drag continues. See video linked below:

https://drive.google.com/file/d/0B9fGr6w-dfLWaGdDcjlyazZaaVU/edit?usp=sharing

The behaviour I expect is the drag to continue even if my mouse leaves the drag handle element and hovers over the iframe element.

Does anybody know how I can fix this?

Thanks,
Max

**Comment by maxmumford** [comment]
blogged a fix here: http://maxmakedesign.co.uk/posts/20

**Comment by mdunc** [comment]
@maxmumford Your link is dead.  Do you have an updated URL?

Edit:  Nevermind, found it here http://www.maxmakedesign.co.uk/development/2013/gridster-breaks-iframe-drag-drop/
