### ISSUE TITLE
Widget cannot take up whole row?

### ISSUE THREAD

**Issue by rcarmo** [ducksboard/gridster.js#27]
I tried to add a widget that was the width of an entire row and gridster apparently gave up on it, positioning the contents of the li randomly. What gives?

**Comment by vieron** [comment]
Hi @rcarmo !

Can you give me more details about this? please :)

If you go to [gridster.net](http://gridster.net) and paste this in the console:

```
gridster.add_widget('<li>Widget</li>', 6, 1, 1, 1);
```

Is something like this what you're trying to do?

**Comment by rcarmo** [comment]
Traveling. Will get back to you on this.
