### ISSUE TITLE
Multi-instance: Drag events delivered to wrong instance (with reproducing code)

### ISSUE THREAD

**Issue by febeling** [ducksboard/gridster.js#272]
When using multiple Gridster instances on the same page, the drag events start and stop are being delivered to a wrong instance. Apparently the last one receives the events. 

I reproduced the problem in the Multi-instance demo page. See febeling@a30551d66547501ffec435421c29f0f38c0ba05f and febeling@79d0feddb754e2ea63e6f57ce69a6f2a6cdce1ed.

If you drag in first grid, the console log message says "grid 2".

**Comment by myabc** [comment]
@febeling Problem was with Gridster options handling (and default options being modified with values of first instance).

The following patch should remediate the problem: https://github.com/myabc/gridster.js/commit/f911c2eebbdb43f1e55edd3f08384d5d80d0ebee

**Comment by febeling** [comment]
I can confirm that PR #273 fixes the problem.

**Comment by febeling** [comment]
Fixed with #273, which has been merged.
