### ISSUE TITLE
Scrolling in box triggers drag action

### ISSUE THREAD

**Issue by donburks** [ducksboard/gridster.js#29]
Scenario is to have a box in gridster which contains a scrollable div. (overflow-y: scroll, and fixed height). If the user scrolls in the box, the drag action begins on mouse up. Which means that the user has completed their interaction with the box and begins to move their mouse away, simultaneously bringing the box with it. 

Does anyone have any suggestions on how I can disable this so that the scroll action on the box disables the draggable functionality of the box, but the user can still grab the box with any other standard mouse interaction and drag it in the layout (as intended)?

**Comment by AlexAllocated** [comment]
The plugin really should give you the option of passing in an element to be used as a drag handle, but in the meantime the workaround I used is to attach a click event to the inner element that you don't want to trigger drag on. In that click event call event.stopPropagation();. This prevents the click event from bubbling up to the parent element where gridster then grabs it.

I basically put two elements in my widgets. One DIV to be used as the title bar/drag handle and another DIV to contain the content.

```
<div class="widgetTitle">Widget 1</div>
<div class="widgetContent" style="overflow: auto;">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet neque sapien. Ut at porta eros. Mauris justo turpis, posuere at pellentesque sed, faucibus vel odio. Vestibulum luctus lorem leo.
</div>
```

Then I just stop propagation on the content DIV's click event.

```
$('.widgetContent').click(function (e) {
    e.stopPropagation();
});
```

Now clicking inside the content DIV will not trigger Gridster's drag action at all. That includes scrolling the DIV if it overflows.

**Comment by manavo** [comment]
I've made some changes to the jquery.draggable.js in this pull request which allows specifying a drag handle selector: https://github.com/ducksboard/gridster.js/pull/59
