### ISSUE TITLE
min_rows behavior

### ISSUE THREAD

**Issue by dustmoo** [ducksboard/gridster.js#30]
Hi ducksboard!

Great work on this library!

I am working on a fork of this to add some behavior and and options that I need. And I am wondering about the min_rows behavior.

It seems to limit the widgets when you try to drag the widget to the bottom of the columns, but not prevent other widgets from being displaced down, is this intentional?

**Comment by vieron** [comment]
Hi @dustmoo!

I improve the way rows are calculated some days ago. Now, the number of rows is given by the sum of the heights (size_y) of all widgets. So, if you have in your grid:
- 6 widgets with size_y: 2
- 2 widgets with size_y: 4
- 4 widgets with size_y: 1

The number of rows will be: 6_2 + 2_4 + 4*1 = 24. If this result is smaller than min_cols option, min_cols value will be used. 

This is recalculated each time add_widget or resize_widget method are invoked.

I hope these changes will come better for what you're doing.

Thanks for the feedback!

**Comment by dustmoo** [comment]
Awesome! Thanks for the update!
