### ISSUE TITLE
Droping element from draggable(jquery ui) list to Grid(Gridster)

### ISSUE THREAD

**Issue by rainbow99984** [ducksboard/gridster.js#302]
Hi, this is not issue but kind of implementation question.
I'm trying to drop element from another list which is jquery draggable to Grid.
 I can add using draggable stop function using gridster.add_widget . But I'm unable to get the row/col information to insert at correct place, draggable ui element gives me offset, is it anyway helpful to get underlying element so that i can push the new element at correct position. 
Anyone have achieved this?
Thanks.

**Comment by rainbow99984** [comment]
I fixed my problem using  current element on grid. its approximation but working for me, I put on mouse enter event on grid elements and collected the current element to which Element is dragged for droping, thus taking the row,col and added using add_widget with proper row,col.
Thanks.

**Comment by vin-san** [comment]
Hi,
I try to do the exact same thing (with angularjs gridster) but I can't figure out how to do it.
Can you drop some of your code with explainations ?
Thanks.
