### ISSUE TITLE
Drag & Resize Containment

### ISSUE THREAD

**Issue by cizgidekiadam** [ducksboard/gridster.js#306]
Hi,
Great job, thanks !

Are you planning drag & resize containment options? 
Also interesting about widget sizes as percent which is relative to parent.

**Comment by adamyonk** [comment]
I would also like to see percentage-based widget dimensions. Would be very nice for creating fluid-width grids.

**Comment by vieron** [comment]
What means "drag & resize containment options"?

Widget sizes as percents will not be implemented in gridster, but there are other open issues discussing that.
