### ISSUE TITLE
Multiple Instances on same Page

### ISSUE THREAD

**Issue by claravanstaden** [ducksboard/gridster.js#308]
I've got tabs, with a gridster instance on each page. I make objects of these gridsters, and add widgets. Everything works fine, except for the dragging. Only the last instantiation of a gridster object calls the drag stop callback. The rest drag starts, drag, but does not invoke the stop callback. I have used PR #273, but the problem persists. Can anyone give me an idea of what the problem might be?

**Comment by claravanstaden** [comment]
On a side note, I am using namespaces.

**Comment by davidpelayo** [comment]
Could you please post here a codepen or jsfiddle to see the problem live?

**Comment by vieron** [comment]
Drag callbacks are working with multiple gridster instances on same page. No jsfiddle test so closing the issue...
