### ISSUE TITLE
Strange overlapping issue

### ISSUE THREAD

**Issue by simplenotezy** [ducksboard/gridster.js#309]
Hello there.

I am experiencing a quite strange overlapping issue. I have already searched around, and tried to implement other solutions (regarding this issue), but nothing have worked.

I don't know if we experience the same kind of overlapping (after a short google search).

As you can see on this screenshot: https://www.dropbox.com/s/2myq7d4m4x7h64m/Screenshot%202014-02-06%2016.34.15.png

I am trying to move around a very long box (620 px / 21 y's), but the placeholder only indicates that it is way smaller.

Any clue to what is wrong?

**Comment by vieron** [comment]
Screenshot link is broken. And please don't submit this kind of issues without a jsfiddle/codepen demo scenario.
