### ISSUE TITLE
Dynamic addition of widgets is broken

### ISSUE THREAD

**Issue by artem-karpenko** [ducksboard/gridster.js#310]
I've updated from 0.2.1 version to 0.4.1 and it gridster now appears faulty when adding widgets dynamically. Demo http://gridster.net/demos/adding-widgets-dynamically.html also suffers from this.

**Comment by halfdan** [comment]
Confirmed - the widgets are only appearing on the most left column when dragged.

**Comment by vieron** [comment]
Thanks for the notice! Fixed here 4774597834300601fc81d5111a31a8c1672c55e1.
