### ISSUE TITLE
Gridster issue with dynamic with of blocks

### ISSUE THREAD

**Issue by sushil-r** [ducksboard/gridster.js#312]
hi ,

if i am having equal size four blocks each in two row   and changing the size of second block of first row.
it automatically move  to the next row but within same column..and is moving the the next row block to a new row

i want this to move it to the next blank row rather than moving the next occupied row and first column.

please help ....thanks in advance.

**Comment by vieron** [comment]
Please post a codepen/jsfiddle with a working demo when submitting an issue
