### ISSUE TITLE
How to save the new added widget's state

### ISSUE THREAD

**Issue by PoojaSSW** [ducksboard/gridster.js#315]
I added a new widget using this function mentioned in the gridster documentation:
$('.js-resize-random').on('click', function() {
        gridster.add_widget('<li class="new">The new widget...</li>', 2, 2);
    });

I want to save the state after adding this new widget, so that on refresh I should be able to see this added widget on display.
Any ideasss????

Thanks

**Comment by davidpelayo** [comment]
On refreshing your browser you mean or... what exactly?

**Comment by vieron** [comment]
You should get widget positions with gridster.serialize(), store them somewhere (db, cookies, local storage...) and then add widgets one by one to the grid like in the [Build from serialize example](http://gridster.net/demos/grid-from-serialize.html)
