### ISSUE TITLE
REQUEST \ QUESTION - Is Gridster on a publicly available CDN?

### ISSUE THREAD

**Issue by IntStarFoo** [ducksboard/gridster.js#320]
Hi All,

Is there a publicly available CDN that I can use to link in jsfiddle.net?  The following jsfiddle demonstrates using Gridster with Knockout.  It isn't working because I can't find any publicly available CDN sites.
http://jsfiddle.net/Be4cf/43/

In Searching around for all of this, I noticed that Microsoft has a public CDN that has some good libraries.  http://www.asp.net/ajaxlibrary/cdn.ashx

Sinceuwaz...  Gridster clearly Rocks.  Is there a way to get Gridster pushed up to a Microsoft hosted CDN?

Cheers,

IntStarFoo

**Comment by jimaek** [comment]
Here you go http://www.jsdelivr.com/#!gridster.js

**Comment by IntStarFoo** [comment]
Boom!  Thanks!  http://jsfiddle.net/Be4cf/44/
