### ISSUE TITLE
How to forbid gridster to move widget element down

### ISSUE THREAD

**Issue by aw3s0me** [ducksboard/gridster.js#322]
All board is filled by widgets, without margin. And when i try to move element from one column(1) to another(2) the elements at column 2 just go down out of the board like:

![errormovewidget](https://f.cloud.github.com/assets/3517287/2371767/860d6c26-a82e-11e3-84f7-da7e1be1a6a4.png)

I'd like to forbid placing a widget to a place if there is no place for widgets in the column.

My code:

```
   gridster = $(".gridster > ul").gridster({

          widget_margins: [mySizeDetector.blockMargin, mySizeDetector.blockMargin], 
          widget_base_dimensions: [mySizeDetector.dx, mySizeDetector.dy], /*[width, height]*/
          min_cols: mySizeDetector.xCount,
          min_rows: mySizeDetector.yCount,
  }).data('gridster');
```

Thanks in advance!

**Comment by webdwarf** [comment]
I have the same problem.
with dustmoo gridster version we can use this option "shift_larger_widgets_down: false". it work.
Can we do the same thing with ducksboard version?

**Comment by dustmoo** [comment]
Not currently, I am (slowly) working towards a unification of the library. Currently we are auditing both forks (Main and mine) and trying to figure out what to fix and what to get rid of. Unfortunately, my time is very limited, use the @dustmoo branch now if you can. If there are features that have been added to the main branch that you need in the @dustmoo branch, let me know and I will try to prioritize getting them merged in.

Thanks,

Dustin

On March 13, 2014 at 5:23:39 AM, webdwarf (notifications@github.com) wrote:

I have the same problem.
with dustmoo gridster version we can use this option "shift_larger_widgets_down: false". it work.
Can we do the same thing with ducksborad version?

**Comment by aw3s0me** [comment]
I've included your rep in main.js by require.js like:
"gridster": "vendor/dustmo-gridster.js/dist/jquery.gridster.with-extras.min",
And my result is now:
![error](https://f.cloud.github.com/assets/3517287/2434633/2fe957d6-adb7-11e3-8466-c57caf79e6df.png)

What is going on? :(

Gridster options:
              gridster = $(".gridster > ul").gridster({
                    widget_margins: [mySizeDetector.blockMargin, mySizeDetector.blockMargin],
                    widget_base_dimensions: [mySizeDetector.dx, mySizeDetector.dy],
                    max_cols: mySizeDetector.xCount,
                    max_rows: mySizeDetector.yCount,
                }).data('gridster');

**Comment by dustmoo** [comment]
in your path, dustmoo has two o’s, typo? or the solution to your problem? :)

Thanks,

Dustin

On March 17, 2014 at 2:34:31 AM, Aleksander Korovin (notifications@github.com) wrote:

vendor/dustmo-gridster.js/dist/jquery.gridster.with-extras.min

**Comment by aw3s0me** [comment]
Thank you, I used gridster.css that from the ducksboard repo, so with your css and your library it works fine, but there is still problems with gravity staff. Is it possible to disable it?

Regards,
Aleksander

**Comment by dustmoo** [comment]
I am not exactly clear about the behavior you are describing. Are you trying to stop the widgets from sliding down? 

Are you using the shift_larger_widgets_down option?

Thanks, 

Dustin

**Comment by aw3s0me** [comment]
Yes, I'm trying to stop widgets from sliding down. Yes, I'm using this option, but when i try to move any widget under my static widget. Static widget goes on top.
Regards,
Aleksander

**Comment by dustmoo** [comment]
Hmm.. Could you setup a jsfiddle or otherwise show me an example that I can play around with?

Thanks, 

Dustin

**Comment by aw3s0me** [comment]
I'm tired of this library, I've started to build my own library according to purposes of the project. Gridster is not flexible.
By the way sliding down of the widgets is off now by using your library as i said before. But gravity still exists, I've tried to change the code of library but I'm tired of seeing this code. Probably I can close the theme.
Solution: use dustmoo library.
