### ISSUE TITLE
Problems to upgrade to the new version.

### ISSUE THREAD

**Issue by sosoriov** [ducksboard/gridster.js#324]
Problems to update to new version.
I was working with v0.2.1 version in a project, now I want to update the gridster version but I have some problems to work on it. I think is a css problem but I'm not sure.

In my project I should have an A4 paper size and the user can fill it with gridster. With the previous version I have some problems to adapt the paper and margins for this reason I want to upgrade the version

In the next link you can see the strange behavior with the new version
http://screencast.com/t/7SuLthNn9N

I appreciate your help.

Thanks

**Comment by bedomon** [comment]
It is a bug with jquery ui, I have the same issue...

On of your parent of your ul element (or ul itself) have the position:relative attribute.
Remove it and your widget work better.

The problem with this tips is that gridster did'nt adapt his size after  dragging...

**Comment by bedomon** [comment]
I still have the bug the fix didn't work

**Comment by sosoriov** [comment]
For me It works  thanks

**Comment by bedomon** [comment]
@sosoriov it work with the position trick ?

**Comment by sosoriov** [comment]
@bedomon yes I removed the position:relative and it works

**Comment by mtruneck** [comment]
Or you can set explicitly margin:0;  to your gridster element (UL). The problem is the element has margin: 0px auto; when not dragging which causes centering the element horizontaly.
