### ISSUE TITLE
Calculate grid without html data attributes.

### ISSUE THREAD

**Issue by jakedahn** [ducksboard/gridster.js#33]
I think the biggest fundamental missing feature is the ability to calculate a grid based on a specified set of elements.

As far as I can tell, the only way to get elements positioning properly in a grid is to first define all of the positioning in the html data attributes on each element. data-col and data-row keep showing up as NaN which breaks everything.

It would be great to be able to call $('element').gridster({arguments here}) and based on container size and specified arguments generate values.

**Comment by vieron** [comment]
It's possible to dynamically create widgets without using html data-attrs. There is not an option to pass a collection of widgets but it's easy to do:

```
var gridster = $('ul').gridster({...}).data('gridster');

var collection = [
    ['<li>Widget content</li>', size_x, size_y, col, row],
    ['<li>Widget content</li>', size_x, size_y, col, row],
    ['<li>Widget content</li>', size_x, size_y, col, row],
    ['<li>Widget content</li>', size_x, size_y, col, row],
    ['<li>Widget content</li>', size_x, size_y, col, row],
    ['<li>Widget content</li>', size_x, size_y, col, row],
];

$.each(collection, function(i, widget) {
    gridster.add_widget.apply(gridster, widget);
});
```

I'll tag this issue as a feature-request, to allow doing this through a config option.

Thanks!
