### ISSUE TITLE
Problem to load serialize gridster - wrong widget position

### ISSUE THREAD

**Issue by sosoriov** [ducksboard/gridster.js#330]
I have a problem to load a gridster from serialize object.

Some of my widgets don't appear in the correct position, but in the serialize object they are ok:

My original gridster is:

![image](https://f.cloud.github.com/assets/6907952/2410073/8bac6d98-aab9-11e3-9c1a-cb3e5f26efa9.png)

After serialize and load it appears

![image](https://f.cloud.github.com/assets/6907952/2410082/ab746748-aab9-11e3-9ab2-9dbc84e74e0e.png)

This is the serialize object

![image](https://f.cloud.github.com/assets/6907952/2410098/be2b8380-aab9-11e3-89ad-06f543f5e9d2.png)

Any idea of it?

Thanks

**Comment by BarryatVendorpages** [comment]
Im facing the same problem...

**Comment by sosoriov** [comment]
I still have the problem, any idea?

**Comment by BarryatVendorpages** [comment]
this probaly makes no sense: 
https://github.com/ducksboard/gridster.js/issues/335

**Comment by BarryatVendorpages** [comment]
But the same goes for you, if you want a function to see what I mean let me know ;)

**Comment by sosoriov** [comment]
@BarryatVendorpages it would be very useful for me thanks (y)

**Comment by BarryatVendorpages** [comment]
```
//Sorts tiles according to position
jQuery.fn.tileposition = function() {
    //Gets tile's row
pos = new Array();
$.each(this, function(i,object){
    row = $(object).attr('data-row');
    pos[i] = {'row' : row, 'current' : i};
});

//Sorts tiles position acording to row
sortedpos = pos.sort(function(a,b) {
return parseInt(a.row,10) - parseInt(b.row,10);
});

//Creates posarray used below to sort object
posarray = new Array();
$.each(sortedpos, function(i,value){
    posarray[i] = value.current;
 });

// get copy of DOM element array
var copy = this.toArray();

// don't exceed bounds of arrays
var len = Math.min(posarray.length, copy.length);

for (var i = 0; i < len; i++) {
    var index = posarray[i];
    // make sure incoming index is within bounds of DOM object array
    if (index < copy.length) {         
        // put the index item into the i location
        this[i] = copy[index];
    }
}
return this;
};
```

// The above function basically just reorders dom elements/widget into the appropriate order returning another object... at which point I save each value into a database one after another, later each is recalled in appropriate order, gridster is initiated and all is OKAY :D Sorry about the mess of the above function, be sure to optimize it. Its just a rough. 

```
var correctlistofwidgets = $('#listofwigets > li').tileposition();    
```

Good Luck

**Comment by JulienVerkest** [comment]
@BarryatVendorpages Thanks! Your function solves my problem.

**Comment by sosoriov** [comment]
@BarryatVendorpages Thanks!!! It works

**Comment by topherreynoso** [comment]
Here's a rails helper of the same, in case anyone needs it:

``` ruby
def dashboard_ordered(widgets)
  pos = []
  widgets.each_with_index do |widget,i|
    row = widget['row']
    pos[i] = { row: row, current: i }
  end
  sortedpos = pos.sort_by{|widget| widget[:row]}
  posarray = []
  sortedpos.each_with_index do |widget,i|
    posarray[i] = widget[:current]
  end
  copy = widgets.dup
  len = posarray.count 
  len = copy.count if copy.count < posarray.count
  i = 0
  while i < len
    index = posarray[i]
    if index < copy.count
      widgets[i] = copy[index]
    end
    i += 1
  end
  return widgets
end
```
