### ISSUE TITLE
removing widget doesnt move left

### ISSUE THREAD

**Issue by eperler123** [ducksboard/gridster.js#338]
hello

when i call "gridster.remove_widget" and there is only 1 row .. the widgets do not "move_left"

i.e.. if i have 4 widgets in 1 row...

widget1 | widget2 | widget3 | widget4

and i remove widget2 ...

then i end up with ...

widget1 | <empty cell> | widget3 | widget4

and i was hoping to get ...

widget1 | widget3 | widget4

is this working as designed, or am i doing something wrong ?

please note that if i have more than 1 row, and i remove a widget from the first row... the widgets do "move up"...

i.e.. if i have 2 rows and 2 cols

widget1 | widget2
widget3 | widget4

and i remove widget 1.. widget 3 "moves up" and i end up with ..

widget3         | widget2
<empty cell> | widget4

which is what i expect..

thanks in advance

**Comment by hrosenbauer** [comment]
This is "works as designed". Widgets are only moved to the top but stay in their assigned column.

**Comment by eperler123** [comment]
is there any code sample that could help me figure out how to move them left if there is an open cell ?
I tried a few things and some work but after they run i get unexpected behavior while dragging 

thx
Date: Thu, 3 Apr 2014 01:17:19 -0700

**Comment by vieron** [comment]
This is how gridster works... Maybe you should check other libraries like [Packery](http://packery.metafizzy.co/),  [grid](https://github.com/uberVU/grid) or [shapeshift](http://mcpants.github.io/jquery.shapeshift/)

**Comment by gjp151088** [comment]
I solved this issue 
http://stackoverflow.com/questions/36358231/how-to-position-the-jquery-gridster-after-remove-a-widget/36394886#36394886
