### ISSUE TITLE
Resize Base Widget Sizes Dynamically

### ISSUE THREAD

**Issue by dlabaj** [ducksboard/gridster.js#343]
Does anyone know if it's possible to change the widget_base_dimensions after you have called the constructor.  I basically need to be able change the size of the widgets width when a user resizes their browser.  Thanks.

**Comment by hrosenbauer** [comment]
Have a look at my pull-request: https://github.com/ducksboard/gridster.js/pull/336

**Comment by dlabaj** [comment]
Exactly what I need.  Thanks a bunch.
