### ISSUE TITLE
Moving widgets  and swap the position?

### ISSUE THREAD

**Issue by pravin88** [ducksboard/gridster.js#347]
Currently when I move the widgets, the widget in the bottom is moved up.
Instead I would like to 
1) move the widget from right.
2) even bettter, swap it with the position where ever I drop

Not sure if it is possible with small configuration changes. or needs code changes

Any help would be much appreciated..

**Comment by vieron** [comment]
Not possible with config. Gridster does not support widget swaping.

Maybe you should check [dustmoo fork](https://github.com/dustmoo/gridster.js) or [uverVu/grid](https://github.com/uberVU/grid)
