### ISSUE TITLE
serialize with ids

### ISSUE THREAD

**Issue by antonkulaga** [ducksboard/gridster.js#354]
I do not see any id's in results of serialize method, so how can I know which html element belongs to which widget?

**Comment by hrosenbauer** [comment]
Solution: https://github.com/ducksboard/gridster.js/issues/317

**Comment by antonkulaga** [comment]
Thank you! Maybe you should add this solution to gridster documentation?

**Comment by hrosenbauer** [comment]
It already is: http://gridster.net/#serialize_params_opt
