### ISSUE TITLE
Internet Explorer 11 issues

### ISSUE THREAD

**Issue by stodge** [ducksboard/gridster.js#356]
I'm having a weird issue with IE11. When I load my page my largest portlet (as I call them) is sometimes pushed way down the page. It doesn't snap up to sit underneath the other ones. Also, when I drag smaller portlets around, they sometimes get stuck behind the large one. It's no consistent - I can't reproduce it anymore and it only happened about three times. Has anyone seen anything weird like this? This is part of a larger code base and isn't public, so I can't post anything, sorry.

**Comment by vieron** [comment]
I can't reproduce the issue. Working fine on IE11. Please try to isolate your code and post here a codepen/jsfiddle demo scenario.

Maybe your problem is related to overlapping issues, in that case, there are open issues related to that, no need to open a new one.
