### ISSUE TITLE
Issue when building from serialzed grid layout

### ISSUE THREAD

**Issue by FamiComplex** [ducksboard/gridster.js#359]
In my testing, I found a small issue - when building a grid from existing serialized widgets, once the grid reaches a certain height element jump to the top of the page.

The issue is in the add_widget function, specifically, line 250, "this.add_faux_rows(pos.size_y);". pos has no "size_y" parameter when column and row values exist.

Changing this line to "this.add_faux_rows(size_y)" or readding those parameters to pos fixes the issue. Thanks!

**Comment by vieron** [comment]
Thanks! Fixed in #342 and will be merged soon
