### ISSUE TITLE
add_widget on button click

### ISSUE THREAD

**Issue by marco-gagliardi** [ducksboard/gridster.js#362]
Don't know if it can be considered an actual issue, anyway it seems that the "button onclick handler" can't work properly with the add_widget function. 
Check this out: http://jsfiddle.net/H6dCR/
Adding a widget in the outer scope works properly. Even binding the function to "mouseover" event instead of "click" (on the same button) works fine.

**Comment by BorisKozo** [comment]
I think you forgot to cancel default button action:
http://jsfiddle.net/zbzzn/H6dCR/2/

**Comment by marco-gagliardi** [comment]
Sure, it makes perfectly sense! Thank you!
