### ISSUE TITLE
Cannot drag to rightmost position after using widget_resize_dimensions to bigger size.

### ISSUE THREAD

**Issue by jirontan** [ducksboard/gridster.js#363]
I was using widget_resize_dimensions to resize my widget size, widget_margin and using jquery to modify the sizes. As I resize from a larger size to smaller size, the gridster works fine for me. But alternately, if the widget are resized from smaller size to larger size, the widget are not allowed to move to the rightmost position. If I inspect element and change the value of data-col, it is able to move to that position. Can anyone help on this issue? Thanks.

**Comment by vieron** [comment]
I think the problem here is how you are "using jquery to modify the sizes". Looks like you are resizing manually and gridster is not updating the gridmap. Btw, you should provide a jsfiddle example.
