### ISSUE TITLE
Gridster items don't move after resize_widget()

### ISSUE THREAD

**Issue by Superdrac** [ducksboard/gridster.js#364]
Hi, i made a mod which allow blocks to fit to their content but i have an issue with the moves...

When i call resize_widget() it's ok, my widget is resized, but when i drag another widget above or bellow, the widget that i just resize don't move and the widget that i drag can be put over... 

It's like the widget that i resized was not a gridster object anymore. For it is again able to move like a gridster object, i need to drag it (not necessary on another grid box) but just a little, and it move again when another widget come above or below. 

There is any solutions to this problem ?  

Here, the item bellow the widget dragged must move (there is enough space on the right)
![1grid](https://cloud.githubusercontent.com/assets/6010282/2889564/35f3e950-d51e-11e3-8c59-fcc8e2a196d9.png)

When i drop it goes behind the hovered widget.
![2grid](https://cloud.githubusercontent.com/assets/6010282/2889565/35f5b9c4-d51e-11e3-8717-25af96582651.png)

And when i move it juste a little, it's movable again.
![3grid](https://cloud.githubusercontent.com/assets/6010282/2889566/35f7b102-d51e-11e3-8724-befecee84e59.png)

**Comment by Superdrac** [comment]
Ok, problem solved. For the resizing, i used a mix of jquery resizable() & resize_widget() (it allow me to add some contraints to it) and the resizable() jquery function add some inline styles to the resized item, i just needed to delete them via removeAttr() and it work fine ! 

Thx for your great tool.

**Comment by otisg** [comment]
@Superdrac Should this issue be closed or did you have to modify something that you plan on sharing?

**Comment by Superdrac** [comment]
@otisg This issue can be closed. Thank you!
