### ISSUE TITLE
Add click event to grid element to bring up modal/lightbox

### ISSUE THREAD

**Issue by andieje** [ducksboard/gridster.js#367]
Hello

I am trying to evaluate if gridster is suitable for a project I am working on so I need to know if it is capable of certain things. I will post each issue indivudally so as not be overwhelming
1. Is it possible to add a click event to the grids in gridster so that they open some kind of lightbox of modal panel. In the long term the goal is for this lightbox to submit a form which modifies the grid

Thank you in advance for any help  you can give me on this issue. Your expertise is particularly valued as I am new to jquery and find it hard to test out these things myself

**Comment by Superdrac** [comment]
It's totally possible to add a click event on a grid element. You don't need to open 4 thread.. Delete the other and ask all your questions in the same.

**Comment by andieje** [comment]
Sorry i thought that was preferable. Normally if i ask multiple questions
per thread many of them get neglected, espeially if one issue is complex
and leads to discussion
