### ISSUE TITLE
Widget size update

### ISSUE THREAD

**Issue by CorySchulz** [ducksboard/gridster.js#375]
I have an issue where I'm binding directly to the DOM elements with EmberJS and it's changing the attribute values on the DOM elements to trigger resizing, which works, but then when I go to drag an element it still thinks it's the original size and the background shadow helper during drag isn't updating. Is this an issue or am I just using it wrong? I've tried using the resize_widget call and passing in values but that didn't work properly. Is there a way to resize and reposition in one call and have it actually work? Or am I better off removing the widget and readding it?

**Comment by vieron** [comment]
Changing DOM attribute values directly is not valid, gridster needs to update the gridmap and each widget coords.

`resize_widget` method should work, it will also try to reposition the widget.  But there isn't a method to reposition widgets programmatically. If `resize_widget` doesn't work for you, please send a jsfiddle demo reproducing the issue.
