### ISSUE TITLE
Links inside widget fire when dragging stops.

### ISSUE THREAD

**Issue by AndyAyrey** [ducksboard/gridster.js#38]
Hi there, first off I cannot thank you enough for this plugin—it is seriously _the bomb_ and playing a big part in an application I'm currently working on. 

Sadly a recent update—the changes to the drag/stop callbacks on Aug 13—introduced some undesirable behaviour. If an anchor is inside a widget, and you click on it and begin dragging, the link will fire on MouseUp or when dragging stops. (Not sure which specifically.)

(Desirable behaviour in our application is to have a widget which is dragged around, but when clicked, takes you to another page.)

**Comment by AndyAyrey** [comment]
Managed to resolve this. 

Coffeescript solution from the Backbone app I'm working on:

``` coffeescript
  events:
    'click .player-revert a': 'finishDragging'

  finishDragging: (e) -> 
    e.preventDefault()
    $(@el).removeClass("player-revert")
```

Generic JS solution (untested, should work in theory)

``` javascript
$('.player-revert>a').click(function(e) {
    e.preventDefault()
    $(this).parent().removeClass("player-revert") 
});
```

**Comment by shaundon** [comment]
Thanks for this - it was very useful.
