### ISSUE TITLE
Make size-Y and size-X float numbers?

### ISSUE THREAD

**Issue by p7900** [ducksboard/gridster.js#39]
I have problem with gridster - i have box in grid, loaded data from ajax database so height on box was changed, i want to have box with data-sizey like 3.2349 for example, but when i changed fn.register_widget function on source code from parseInt to parseFloat that dsnt working. What can i do?

**Comment by bmla** [comment]
If I understand it right, gridster works on intervals. So the widget_base_dimensions, along with widget_margins, represent the x and y intervals.

**Comment by vieron** [comment]
@bmla is right. Probably you can wrap the widget content and set the height of this wrapper via javascript. But the widget will overlap with the widgets below.
