### ISSUE TITLE
Arbitrary widget position

### ISSUE THREAD

**Issue by dariobanfi** [ducksboard/gridster.js#409]
Hi, 

I wanted to ask if it's possible to place a widget in an arbitrary position, like bottom right.

At the moment the widget snap always to the closest widget in the same column, so it's not possible put a widget, a space and a widget on the same column.

**Comment by hrosenbauer** [comment]
This is not possible with the current implementation (as it is intended that all widgets snap to the closest one).

**Comment by TitoVince35** [comment]
Aaaargh! Thanks, reburgger.
Have you guys heard of any component that might help with "free" positioning?
