### ISSUE TITLE
Draging problem on Opera Browser

### ISSUE THREAD

**Issue by blacksrc** [ducksboard/gridster.js#41]
Hello
there are some problem while draging the box. the box goes down when you try to move it. I think it's better to test it yourself. I'm not sure that it's a bug or not. But i thought it's better to tell.
## Hope to help.

Siamak.A.M
blacksrc.com

**Comment by vieron** [comment]
For me works as expected in Opera (in OSX). Maybe related with one of the positioning bugs already reported?

Anyway, if you reproduce it again, a screencast is appreciated :)

**Comment by blacksrc** [comment]
Hello
This is the video:
http://youtu.be/8AhlYdH612Y

And this is my code that i've tried:
http://blacksrc.com/doc/myfiles.zip

Browser: Opera 12.2
OS: Windows

Still have the problem
