### ISSUE TITLE
Vertical scroll bar

### ISSUE THREAD

**Issue by StephenLegros** [ducksboard/gridster.js#416]
How to add content in a widget with a vertical scroll bar? If the text or content is too large, the content is embedded on other widgets below. Thank you very much for your response.

**Comment by ninefoldx** [comment]
Have you tried to use "overflow-y: auto; overflow-x: hidden;"?

**Comment by StephenLegros** [comment]
Yes, but it work fine with subtracting the header of 45px :

```
height: 100%;
overflow: auto;
height: -moz-calc(100% - 45px);
height: -webkit-calc(100% - 45px);
height: -o-calc(100% - 45px);
height: calc(100% - 45px);
```
