### ISSUE TITLE
Automatic grid generation based on size

### ISSUE THREAD

**Issue by ghost** [ducksboard/gridster.js#43]
Hi,

Would be great if the plugin can generate the elements position based on the size of the boxes.
This could help for those who want to use in dynamic environment (ex. when user adds the blocks).

**Comment by bmla** [comment]
Something like this https://github.com/ducksboard/gridster.js/issues/33#issuecomment-8022228 ?

**Comment by minicstudio** [comment]
I dont get it how can i do with that. I only know the size attributes.

**Comment by bmla** [comment]
``` javascript
gridster.serialize()
```

will give you row, col, size_x and size_y of all you widgets.
