### ISSUE TITLE
Cannot Drag Widget To Bottom of Grid

### ISSUE THREAD

**Issue by epau** [ducksboard/gridster.js#44]
First off I just want to thank you for the great work you've done. It's awesome!

I want to be able to drag a widget to a row that doesnt have a widget directly above. Right now you cna only drag widgets to a row that is directly under another widget. basically i dont want the widgets to always realign so that they are top-aligned. I want to be able to snap them to any cell in the grid regardless if another widget is directly above or below it.

**Comment by mellson** [comment]
+1

**Comment by gerardo** [comment]
+1

**Comment by vieron** [comment]
Same as #45. There is more activity on the other so I’ll close this.
