### ISSUE TITLE
reset gridster

### ISSUE THREAD

**Issue by ghost** [ducksboard/gridster.js#46]
In an attempt to make gridster responsive i'm removing the list container and re-render with different parameters, it works fine for 2,3 steps but after those gridster doesn't update the values.

This is very strange because i completely remove the old element from the dom ( $('#collections').remove() ).

I have the feeling that gridster doesn't completely reset his previous values.

i've uploaded a simple demo (see app.js from line 106 to line 167) 

http://assets.mountainthemes.com/readie.zip

**update** : i think it's a problem caused by autogenerating styles

**Comment by ghost** [comment]
**solved** i removed this condition inside the "generate_stylesheet" function, is there a way to do that without modify the core ?

`
if ($.inArray(serialized_opts, Gridster.generated_stylesheets) >= 0) {
    return false;
}`

also i manualy remove from the dom the generated stylesheet.

**Comment by johnygold** [comment]
Thanks for pointing this out! I solved this problem as well by removing that part of the code. My problem was that I removed the active gridster element and recreated it dynamically with new dimensions for the widgets. However it kept on using the old values. It would be great if you could introduce a better reset feature for the gridster element.

**Comment by goldnead** [comment]
+1

**Comment by aziz** [comment]
:+1:

**Comment by jgoux** [comment]
I have a similar issue.
I reset gridster by manually remove the <style> tags within the <head> and removing all the content of my <div class="gridster">.
After that I load a new list from a JSON file, I reapply the plugin on it. Everything works fine when I want to drag and drop the element I loaded.
The problems appear when I want to add new elements, the grid becomes buggy, I can't drag the new elements where I want, certains new elements are placed in front of the old ones...
If somebody has a solution...

**Comment by rfink** [comment]
+1

I would patch and submit a pull request if I had time.  My thought was to apply a unique id to each style tag created, and when the gridster instance is destroyed, search for that unique id in the head and remove it from the document.

**Comment by rfink** [comment]
I went ahead and submitted a pull request:  https://github.com/ducksboard/gridster.js/pull/152
