### ISSUE TITLE
Is it possible to nest a gridster within a gridster?

### ISSUE THREAD

**Issue by dafooz** [ducksboard/gridster.js#497]
Hi guys,

First of all, thanks for this wonderful work!

I was wondering if there is a way to nest a gridster within a gridster... I saw the demo with the 2 gridster within the same page but I'm wondering if it's possible to put a gridster inside a gridster in order to have multiple level of customisation.

Thanks in advance for the help and the great job you guys did!

**Comment by ghost** [comment]
i dont see why not . you can have multiple instances of gridster in one page so nesting should be possible

**Comment by dafooz** [comment]
Yeah I gave it a quick try and it seemed to work :) I'll dig into it deeper
next week.

Thanks for the answer ;)
