### ISSUE TITLE
Resizable widget

### ISSUE THREAD

**Issue by cocodrino** [ducksboard/gridster.js#50]
would be nice can resize the widgets, when drag the corner this change its size to 2,3,4... columns or rows...

**Comment by bmla** [comment]
You can use http://gridster.net/#resize_widget_method and do some jQuery magic :)

``` javascript
.resize_widget( $widget, [size_x], [size_y] )
```

**Comment by cocodrino** [comment]
thanks!!...it works great..

**Comment by jeanfs** [comment]
Cocodrino, can you post here how did you do that? I need to do this at the project I'm working on, but I'm not that good in javascript as I wish. So if you don't mind, please, post the "jQuery magic" you did. =)

I tried to use it with jQuery UI resizable, but it didn't work. =/
