### ISSUE TITLE
How to determine the row/column related to a JQuery X/Y coordinate?

### ISSUE THREAD

**Issue by gerardo** [ducksboard/gridster.js#51]
Currently, I can add widgets to the grid via gridster.add_widget(..) using the row and column parameters. But I'd like to add a widget in a row/column related to a X/Y coordinate like the one from a Jquery event.

Every JQuery event receives an "event" object with a pageX and pageY attribute, which I use to know where the user double clicked. I want to be able to add_widget in the cell enclosing that x/y point.

How do I get a row/column number based on that x/y coordinate with the current API? I don't see anything like it, the closest thing seems to be Coords but I'm not sure. An alternate add_widget ( x, y) method would be great, though :-)

**Comment by gerardo** [comment]
Somebody?

**Comment by vieron** [comment]
The gridster API returns a faux_grid attribute which is an array with all the instances of the Coords class representing each cell of the grid. Accessing to CoordsInstance.coords you get x1, x2, y1, y2 points that represents the cell position. Maybe you can play with this.

The on_overlap_start callback of the Collision class would be perfect, but by now it only works with DOM elements or Coords objects. It would be nice something like $(mouseEvent).collision(colliders, options);

**Comment by gerardo** [comment]
Thanks! faux_grid did the trick. This is my implementation (coffeescript):

``` coffeescript
 _.every @grid.faux_grid, (elem) ->
                c = elem.coords
                if c.x1 < ejex < c.x2  and c.y1 < ejey < c.y2
                  col = elem.data.col
                  row = elem.data.row

                   # do stuff with matching cell

                  return false
                return true
    @
```
