### ISSUE TITLE
Destroy problem with multiple gridster

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [ducksboard/gridster.js#513]
Namespace not used on destroy method. 

Destroying any gridster on DOM effects all gridsters.

http://jsfiddle.net/iboylmz/L0vyevgr/1/

**Comment by bondt** [comment]
Hey @iboylmz,

I've updated the script to 0.5.6 and it works. Check out: http://jsfiddle.net/b0ndt/L0vyevgr/2/
