### ISSUE TITLE
Drag not working on Microsoft Surface with touch

### ISSUE THREAD

**Issue by mportuga** [ducksboard/gridster.js#517]
While testing your demo on devices, I realized that I can't rearrange tiles on the Microsoft Surface with touch. It works fine on other touch devices (LG G2, iPad), and actually even works fine on the Surface with a mouse plugged in. But with the touch screen interface, it seems like the Surface is not retaining the fact that a touch and hold is being done to rearrange.

**Comment by CurlyTailCode** [comment]
In your css, add 'touch-action: none' to the ul where gridster is.  That fixes it for 8.1 devices (untested on 8.0).  See https://jsfiddle.net/mgsrss0u/1/
