### ISSUE TITLE
destroy() and init() duplicate gridster events

### ISSUE THREAD

**Issue by ghost** [ducksboard/gridster.js#527]
Hi all, I am using destroy and init when the window hits certain breakpoints to make the grid responsive but with fixed sizes, but after the init, all events are duplicated, is this a know bug, is there a workaround?

**Comment by mdconaway** [comment]
I have a fix for this.  I will generate a pull request to fix your issue.

**Comment by mdconaway** [comment]
Also, if you need the fix ASAP, I have a patched version of gridster contained within my project here: https://github.com/mdconaway/vchat

You can find it in the application "vendor/lib" folder.

**Comment by ghost** [comment]
Thank you, this solved a big problem for us!
With this, I've managed to make a responsive grid that changes the col number dynamically if as they fit the screen :)

**Comment by Qlipoth** [comment]
mdconaway, its very very very COOOOOOOOOOOOOOOOOL !!!
