### ISSUE TITLE
Max Rows

### ISSUE THREAD

**Issue by jamescoverdale** [ducksboard/gridster.js#55]
Hi, 

I can limit the colums by setting the width of the div or the <ul> tag, so that in my case there is only space for 2 columns, but the height is ignored, so widgets can be placed in one column and end up with lots of rows.

I want to limit it to a 2 x 2 grid, is this possible?

james.

**Comment by MichaelPaulukonis** [comment]
See notes @  [Allow horizontal swapping without creating new rows](https://github.com/ducksboard/gridster.js/issues/54)

**Comment by vieron** [comment]
Duplicate of #54
