### ISSUE TITLE
Inputs and Textareas inside widgets behave inconsistently.

### ISSUE THREAD

**Issue by AndyAyrey** [ducksboard/gridster.js#56]
If you place an <input> or a <textarea> inside of a widget, some really weird things start happening:

In Webkit (only tested on desktop), fields behave in a mostly correct fashion: you are able to select text and shift the caret with the arrow keys + modifiers. (CMD/CTRL to jump to start of line, etc.) Clicking on the field will correctly position the caret at the position clicked. However, CTRL/CMD-A does not work, neither does right-click, Select All.

In Gecko, you are able to Select All; but CMD/CTRL + Arrow will not jump to the beginning of a line as it would in a regular form field. ALT still works for jumping between words, however. Additionally, when you click on the field, the cursor will only ever appear at the beginning of the field in question, instead of at the clicked location.

Not sure what's happening here—whether it's simply an events-related issue or something deeper. Would greatly appreciate any advice on how we might possibly deal with this. 

Kick-ass plugin, by the way. We're using it in a **big** way in an upcoming beta of our app!

**Comment by vieron** [comment]
It was related with the onselectstart event, used to prevent selection when dragging widgets. Thanks for reporting the error! Let us know when we can see what you're doing with gridster ;)
