### ISSUE TITLE
How to disable drag & drop?

### ISSUE THREAD

**Issue by newgi** [ducksboard/gridster.js#58]
I don't understand how to turn off the drag & drop completely. Can you show me an example please?

Thanks

**Comment by hoyer-io** [comment]
You can do it directly when you initialize the grid e.g.

$(".grid > ul").gridster({
            widget_margins: [6, 6],
            widget_base_dimensions: [160, 213],
            min_cols: 4,
            min_rows: 3,
            widget_selector: ">li",
            avoid_overlapped_widgets: false
        }).data('gridster').disable();

Or if you want to do it later, assign the gridster object to a variable and disable it later:

var grid = $(".grid > ul").gridster({
            widget_margins: [6, 6],
            widget_base_dimensions: [160, 213],
            min_cols: 4,
            min_rows: 3,
            widget_selector: ">li",
            avoid_overlapped_widgets: false
        }).data('gridster');

grid.disable();

**Comment by newgi** [comment]
Great, thanks a lot!
