### ISSUE TITLE
Adding Content

### ISSUE THREAD

**Issue by samcov** [ducksboard/gridster.js#6]
I was looking at the demo(btw, it would be nice to include it in the dist.), and I couldn't see where you added sprite.png on the drag element.

However, this has awesome possibilities, and I'm pleased with the cross browser support.

**Comment by vieron** [comment]
sprite.png on the drag element is declared here https://github.com/ducksboard/gridster.js/blob/gh-pages/assets/css/style.css#L369  Its only for the demo. The distributable stylesheet only includes the basic CSS needed to make gridster work.

You can checkout gh-pages branch to see how the demo is made. Its possible we add in a future a directory with different  examples of gridster usage.

**Comment by samcov** [comment]
Thanks!
