### ISSUE TITLE
Added widgets do not move to next row when current row is full

### ISSUE THREAD

**Issue by alexcason** [ducksboard/gridster.js#60]
When adding widgets I have noticed that when the current row is full, the next widget is no longer placed on the next row down. New widgets are just placed at the end of the first row.

When the `add_faux_cols` method was comitted (3d5077dd7b7473c229425cad087d9a94562824e6) it was used in the `add_widget` method. From what I can see, this means that when `this.cols` is used in the `can_move_to` method to determine if the widget would be outside of the grid, the number of cols in the grid increases by one each time a new widget is added and the `add_faux_cols` method is called.

Is this expected behaviour?

**Comment by alexcason** [comment]
Thanks for the fix.

**Comment by vieron** [comment]
Thank you for reporting it.
