### ISSUE TITLE
removing widgets leaves grid map 

### ISSUE THREAD

**Issue by lhammond** [ducksboard/gridster.js#63]
when I remove all of the widgets except for one which I need to remain, and add some widgets back .. the new widgets are added below where the old ones were .. as though the grid map is still being used by gridster

is there a way to force gridster to refresh it's grid map?

also, is there a better way to remove all widgets?

```
$.each($(".gridster li"), function(index, obj){
    if($(this).attr("id")!="settings"){
      self.gridster.remove_widget(obj);
    }
});
```

**Comment by lhammond** [comment]
I think this due to the fact that remove_widget does not remove the element from the DOM.
I was expecting remove_widget to remove the widget from the grid and the dom.

I added a remove() call after remove_widget to remove the element from the dom.

It works, but when I add back a widget with the same id, I get a "TypeError: el_grid_data is undefined" in firebug.

**Comment by praveenaj** [comment]
This didn't fix the bug in my case. I had to add few extra lines to fn.move_widget_up function to avoid the error. 

``` javascript
  fn.move_widget_up = function($widget, y_units) {
        if(typeof $widget.coords().grid === 'undefined'){
            this.register_widget($widget);
        }
        // rest of the code
    };
```

**Comment by xmikew** [comment]
praveenaj, this fixed my issue as well. Thanks much. This bug is present in dustmoo fork also.

**Comment by castronet** [comment]
I've the same problem, thanks praveenaj and xmikew for your comments.

**Comment by nzmedet** [comment]
fork it! ) thanks that works +1 to carma

**Comment by harshmsp** [comment]
Hello All and @praveenaj,
When i am trying to remove multiple widget at a time, then it will create issue.
Some elements are removed but not resize and that poriton display empty and after that move_widget_up not works perfectly.

I have 12 column \* 10 row widgets where few box i want to remove so i am remove through loop and it cause a problem

here another loop to list of li which i want to remove
_tideid = li id;
                 $(".gridster ul li").each(function (e) {
                    var that = this;
                    var _tideid1 = parseInt($(that).data("tideid"));
                    if (_tideid1 == _tideid) {
                        var gridsterdata = $(".gridster ul").gridster().data('gridster');
                        gridsterdata.remove_widget($(this), true);
                    }
                });

with this code it not remove correct way and error comes on drag drop and move_widget_up

Please help

**Comment by rajivmg** [comment]
Thanks for the solution @praveenaj . It fixes the error and works without any problem.

**Comment by hasekrx** [comment]
In my application i had to remove the Element from the dom after use the remove_widget function and put a validation to prevent the card to moveup inside the remove_widget function in this part:

$el.fadeOut($.proxy(function() {
    $el.remove();
    $nexts.each($.proxy(function(i, widget) {
        if($(widget).coords().grid)
        {
            this.move_widget_up( $(widget), wgd.size_y );
        }
    }, this));
inside the $next.each i did a validation verifying if the coords are not undefined and never had the problem again! i don't think this is the better solution but it is working :)
