### ISSUE TITLE
Adding a block creates duplicates

### ISSUE THREAD

**Issue by WDKevin** [ducksboard/gridster.js#8]
I've created my own barebones demo and when using the add_widget function to add a new block, 2 blocks are always added rather than one. They are added on top of each other so you don't see it until you drag the first one away. When looking at the code, this is the generated code:

<li class="new gs_w" data-col="1" data-row="1" data-sizex="1" data-sizey="1" style="display: list-item; "></li>
<li data-col="1" data-row="1" data-sizex="1" data-sizey="1" class="gs_w" style="display: list-item; "></li>

Both of those elements are created.

**Comment by WDKevin** [comment]
My code was removed, but it creates 2 LI elements with different properties.

**Comment by WDKevin** [comment]
I solved the problem. It was a result of copy/pasting the code from your website for the add_widget function. You're missing the / in the closing LI tag, so it gives to open LI tags instead, rendering 2 elements.

**Comment by nkostadinov** [comment]
Yeah, I also got confused about that. May be you should edit the demo.
