### ISSUE TITLE
Multiple Grids on a single Page (ajax loading) - JS getting very slow

### ISSUE THREAD

**Issue by JoschaP** [ducksboard/gridster.js#95]
Hi all,
I have developed a system to load multiple grids on a single page (infinity scroll).
It works perfectly.

But there is another Problem.
As more as grids are loaded on the page, the hole javascript events getting slower and slower.

There is an very simple click event (bind method) on an single div element on the page (#gridContentSettings). 

If i´ve loaded only one gridster (up to 5), the click event fires instantly without any delay.
If i´ve loaded multiple gridster (10 and more), the click event  on the same element gets slower and slower.

There is no other event bind on that click trigger or something else.
The click event is init on doc ready and unique. (tested with simple alert('test'), nothing more...)

Whats the problem here?

**Comment by Kaherdin** [comment]
Can you show us an example ?

**Comment by ghost** [comment]
![logo-template](https://f.cloud.github.com/assets/2798859/122092/432647c4-6e2e-11e2-9cbb-16bb9eb9dbf1.png)
